package com.srini.hibpojogen.protein_tracker.factories.proteinTracker;

import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.BeanNameAware;

import com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker.*;

/** 
 * DAO factory implementation.
 * @author autogenerated
 */
@Component
public class HibernateProteinTrackerDaoFactory implements ApplicationContextAware, BeanNameAware {
	/** Placeholder for an instance. */
	private static HibernateProteinTrackerDaoFactory instance;
	/** Internal state. */
	private static ApplicationContext context = null;
	/** Bean Name. */
	private static String beanName;

	/** Return an instance of this class.
	 * @return an instance of this class
	 */
	public static synchronized HibernateProteinTrackerDaoFactory getInstance() {
		if (instance == null) {
			instance = (HibernateProteinTrackerDaoFactory) context.getBean(beanName);
		}
		return instance;
	}

	/**
	 * Sets a Spring Application Context object.
  	 * @param ctxt ApplicationContext to set
	 * @throws BeansException on spring error
	 */
	@Autowired
	public void setApplicationContext(ApplicationContext ctxt)
			throws BeansException 
	{
		context = ctxt;
	}

	/**
	* 
	* {@inheritDoc}
	* 
	* @see org.springframework.beans.factory.BeanNameAware#setBeanName(java.lang.String)
	*/
	public void setBeanName(String name) {
		beanName = name;
	}

	/**
	 * Return the requested bean from the context, throwing a RuntimeException on error.
	 *
	 * @param beanName to return
	 * @return the bean requested.
	 */
	public static Object getBean(String beanName) {
		Object result = context.getBean(beanName);
		if (result == null) { 
			throw new IllegalStateException(String.format("Could not find bean '%s'. Did you set the right component scanning?", beanName));
		} 
		
		return result;
	}

	
	/**
	 * Returns a GoalalertDao instance.
	 * 
	 * @return a GoalalertDao instance
	 */
	public static GoalalertDao getGoalalertDao() {
		return (GoalalertDao) getBean("goalalertDaoImpl"); 
	}
	/**
	 * Returns a ProteindataDao instance.
	 * 
	 * @return a ProteindataDao instance
	 */
	public static ProteindataDao getProteindataDao() {
		return (ProteindataDao) getBean("proteindataDaoImpl"); 
	}
	/**
	 * Returns a UserGoalalertDao instance.
	 * 
	 * @return a UserGoalalertDao instance
	 */
	public static UserGoalalertDao getUserGoalalertDao() {
		return (UserGoalalertDao) getBean("userGoalalertDaoImpl"); 
	}
	/**
	 * Returns a UserhistoryDao instance.
	 * 
	 * @return a UserhistoryDao instance
	 */
	public static UserhistoryDao getUserhistoryDao() {
		return (UserhistoryDao) getBean("userhistoryDaoImpl"); 
	}
	/**
	 * Returns a UsersDao instance.
	 * 
	 * @return a UsersDao instance
	 */
	public static UsersDao getUsersDao() {
		return (UsersDao) getBean("usersDaoImpl"); 
	}

}
