package com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.srini.hibpojogen.protein_tracker.model.obj.proteinTracker.Goalalert;
import org.springframework.stereotype.Repository;
import com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker.GoalalertDao;
 
 
/**
 * DAO for table: Goalalert.
 * @author autogenerated
 */
@Repository
public class GoalalertDaoImpl extends GenericHibernateDaoImpl<Goalalert, Integer> implements GoalalertDao {
	
	/** Constructor method. */
		public GoalalertDaoImpl() {
			super(Goalalert.class);
		}
	}

