package com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.srini.hibpojogen.protein_tracker.model.obj.proteinTracker.Proteindata;
import org.springframework.stereotype.Repository;
import com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker.ProteindataDao;
 
 
/**
 * DAO for table: Proteindata.
 * @author autogenerated
 */
@Repository
public class ProteindataDaoImpl extends GenericHibernateDaoImpl<Proteindata, Integer> implements ProteindataDao {
	
	/** Constructor method. */
		public ProteindataDaoImpl() {
			super(Proteindata.class);
		}
	}

