package com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.srini.hibpojogen.protein_tracker.model.obj.proteinTracker.Userhistory;
import org.springframework.stereotype.Repository;
import com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker.UserhistoryDao;
 
 
/**
 * DAO for table: Userhistory.
 * @author autogenerated
 */
@Repository
public class UserhistoryDaoImpl extends GenericHibernateDaoImpl<Userhistory, Integer> implements UserhistoryDao {
	
	/** Constructor method. */
		public UserhistoryDaoImpl() {
			super(Userhistory.class);
		}
	}

