package com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.srini.hibpojogen.protein_tracker.model.obj.proteinTracker.Users;
import org.springframework.stereotype.Repository;
import com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker.UsersDao;
 
 
/**
 * DAO for table: Users.
 * @author autogenerated
 */
@Repository
public class UsersDaoImpl extends GenericHibernateDaoImpl<Users, Integer> implements UsersDao {
	
	/** Constructor method. */
		public UsersDaoImpl() {
			super(Users.class);
		}
	}

