package com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.srini.hibpojogen.protein_tracker.model.obj.proteinTracker.UserGoalalert;
import org.springframework.stereotype.Repository;
import com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker.UserGoalalertDao;
import com.srini.hibpojogen.protein_tracker.model.obj.proteinTracker.UserGoalalertPK;
 
/**
 * DAO for table: UserGoalalert.
 * @author autogenerated
 */
@Repository
public class UserGoalalertDaoImpl extends GenericHibernateDaoImpl<UserGoalalert, UserGoalalertPK> implements UserGoalalertDao {
	
	/** Constructor method. */
		public UserGoalalertDaoImpl() {
			super(UserGoalalert.class);
		}
	}

