package com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.srini.hibpojogen.protein_tracker.model.obj.proteinTracker.UserGoalalertPK;
import org.springframework.stereotype.Repository;
import com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker.UserGoalalertPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: UserGoalalertPK.
 * @author autogenerated
 */
@Repository
public class UserGoalalertPKDaoImpl extends GenericHibernateDaoImpl<UserGoalalertPK, Serializable> implements UserGoalalertPKDao {
	
	/** Constructor method. */
		public UserGoalalertPKDaoImpl() {
			super(UserGoalalertPK.class);
		}
	}

