package com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.srini.hibpojogen.protein_tracker.model.obj.proteinTracker.Goalalert;
 
/**
 * DAO interface for table: Goalalert.
 * @author autogenerated
 */
public interface GoalalertDao extends GenericDAO<Goalalert,  Integer>  {
	// constructor only
}

