package com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.srini.hibpojogen.protein_tracker.model.obj.proteinTracker.Proteindata;
 
/**
 * DAO interface for table: Proteindata.
 * @author autogenerated
 */
public interface ProteindataDao extends GenericDAO<Proteindata,  Integer>  {
	// constructor only
}

