package com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.srini.hibpojogen.protein_tracker.model.obj.proteinTracker.Userhistory;
 
/**
 * DAO interface for table: Userhistory.
 * @author autogenerated
 */
public interface UserhistoryDao extends GenericDAO<Userhistory,  Integer>  {
	// constructor only
}

