package com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.srini.hibpojogen.protein_tracker.model.obj.proteinTracker.UserGoalalertPK;
import java.io.Serializable;
/**
 * DAO interface for table: UserGoalalertPK.
 * @author autogenerated
 */
public interface UserGoalalertPKDao extends GenericDAO<UserGoalalertPK,  Serializable>  {
	// constructor only
}

