package com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.srini.hibpojogen.protein_tracker.model.obj.proteinTracker.UserGoalalert;
import com.srini.hibpojogen.protein_tracker.model.obj.proteinTracker.UserGoalalertPK;
/**
 * DAO interface for table: UserGoalalert.
 * @author autogenerated
 */
public interface UserGoalalertDao extends GenericDAO<UserGoalalert,  UserGoalalertPK>  {
	// constructor only
}

