package com.srini.hibpojogen.protein_tracker.model.dao.proteinTracker;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.srini.hibpojogen.protein_tracker.model.obj.proteinTracker.Users;
 
/**
 * DAO interface for table: Users.
 * @author autogenerated
 */
public interface UsersDao extends GenericDAO<Users,  Integer>  {
	// constructor only
}

